export interface CountryMapShape {
  name: string;
  isoA2: string;
  path: string;
  labelX: number;
  labelY: number;
  aliases: readonly string[];
}
export const WORLD_COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
] as const;

export type WorldCountry = typeof WORLD_COUNTRIES[number];

export const COUNTRY_DESTINATION_ALIASES: Record<string, readonly string[]> = {
  "Afghanistan": ["Afghanistan"],
  "Albania": ["Albania"],
  "Algeria": ["Algeria"],
  "Andorra": ["Andorra"],
  "Angola": ["Angola"],
  "Antigua and Barbuda": ["Antigua and Barbuda"],
  "Argentina": ["Argentina"],
  "Armenia": ["Armenia"],
  "Australia": ["Australia", "brisbane", "melbourne", "perth", "sydney"],
  "Austria": ["Austria", "vie", "vienna", "wien"],
  "Azerbaijan": ["Azerbaijan"],
  "Bahamas": ["Bahamas"],
  "Bahrain": ["Bahrain"],
  "Bangladesh": ["Bangladesh"],
  "Barbados": ["Barbados"],
  "Belarus": ["Belarus"],
  "Belgium": ["Belgium", "bru", "brussels", "bruxelles"],
  "Belize": ["Belize"],
  "Benin": ["Benin"],
  "Bhutan": ["Bhutan"],
  "Bolivia": ["Bolivia"],
  "Bosnia and Herzegovina": ["Bosnia and Herzegovina"],
  "Botswana": ["Botswana"],
  "Brazil": ["Brazil", "rio de janeiro", "sao paulo", "são paulo"],
  "Brunei": ["Brunei"],
  "Bulgaria": ["Bulgaria"],
  "Burkina Faso": ["Burkina Faso"],
  "Burundi": ["Burundi"],
  "Cabo Verde": ["Cabo Verde"],
  "Cambodia": ["Cambodia"],
  "Cameroon": ["Cameroon"],
  "Canada": ["Canada", "montreal", "toronto", "vancouver", "yyz"],
  "Central African Republic": ["Central African Republic"],
  "Chad": ["Chad"],
  "Chile": ["Chile"],
  "China": ["China"],
  "Colombia": ["Colombia"],
  "Comoros": ["Comoros"],
  "Congo": ["Congo"],
  "Costa Rica": ["Costa Rica"],
  "Cote d'Ivoire": ["Cote d'Ivoire"],
  "Croatia": ["Croatia"],
  "Cuba": ["Cuba"],
  "Cyprus": ["Cyprus"],
  "Czechia": ["Czechia", "czech republic", "prague", "praha", "prg"],
  "Democratic Republic of the Congo": ["Democratic Republic of the Congo"],
  "Denmark": ["Denmark", "copenhagen", "cph", "kopenhagen"],
  "Djibouti": ["Djibouti"],
  "Dominica": ["Dominica"],
  "Dominican Republic": ["Dominican Republic"],
  "Ecuador": ["Ecuador"],
  "Egypt": ["Egypt", "cairo", "hurghada", "sharm el sheikh"],
  "El Salvador": ["El Salvador"],
  "Equatorial Guinea": ["Equatorial Guinea"],
  "Eritrea": ["Eritrea"],
  "Estonia": ["Estonia"],
  "Eswatini": ["Eswatini"],
  "Ethiopia": ["Ethiopia"],
  "Fiji": ["Fiji"],
  "Finland": ["Finland", "hel", "helsinki"],
  "France": ["France", "bordeaux", "cdg", "lyon", "lys", "marseille", "nce", "nice", "ory", "paris", "toulouse"],
  "Gabon": ["Gabon"],
  "Gambia": ["Gambia"],
  "Georgia": ["Georgia"],
  "Germany": ["Germany", "ber", "berlin", "bre", "bremen", "cgn", "cologne", "dortmund", "dtm", "dus", "dusseldorf", "düsseldorf", "fra", "frankfurt", "haj", "ham", "hamburg", "hannover", "koln", "köln", "leipzig", "lej", "muc", "muenchen", "munich", "münchen", "nue", "nuremberg", "nürnberg", "str", "stuttgart"],
  "Ghana": ["Ghana"],
  "Greece": ["Greece", "ath", "athen", "athens"],
  "Grenada": ["Grenada"],
  "Guatemala": ["Guatemala"],
  "Guinea": ["Guinea"],
  "Guinea-Bissau": ["Guinea-Bissau"],
  "Guyana": ["Guyana"],
  "Haiti": ["Haiti"],
  "Honduras": ["Honduras"],
  "Hungary": ["Hungary", "bud", "budapest"],
  "Iceland": ["Iceland"],
  "India": ["India", "bangalore", "delhi", "mumbai"],
  "Indonesia": ["Indonesia", "bali", "denpasar", "jakarta"],
  "Iran": ["Iran"],
  "Iraq": ["Iraq"],
  "Ireland": ["Ireland", "dub", "dublin"],
  "Israel": ["Israel"],
  "Italy": ["Italy", "fco", "firenze", "florence", "lin", "milan", "milano", "mxp", "nap", "naples", "napoli", "roma", "rome", "vce", "venezia", "venice"],
  "Jamaica": ["Jamaica"],
  "Japan": ["Japan", "hnd", "kyoto", "nrt", "osaka", "tokyo"],
  "Jordan": ["Jordan"],
  "Kazakhstan": ["Kazakhstan"],
  "Kenya": ["Kenya"],
  "Kiribati": ["Kiribati"],
  "Kuwait": ["Kuwait"],
  "Kyrgyzstan": ["Kyrgyzstan"],
  "Laos": ["Laos"],
  "Latvia": ["Latvia"],
  "Lebanon": ["Lebanon"],
  "Lesotho": ["Lesotho"],
  "Liberia": ["Liberia"],
  "Libya": ["Libya"],
  "Liechtenstein": ["Liechtenstein"],
  "Lithuania": ["Lithuania"],
  "Luxembourg": ["Luxembourg"],
  "Madagascar": ["Madagascar"],
  "Malawi": ["Malawi"],
  "Malaysia": ["Malaysia", "kuala lumpur"],
  "Maldives": ["Maldives"],
  "Mali": ["Mali"],
  "Malta": ["Malta"],
  "Marshall Islands": ["Marshall Islands"],
  "Mauritania": ["Mauritania"],
  "Mauritius": ["Mauritius"],
  "Mexico": ["Mexico", "cancun", "cancún", "mexico city"],
  "Micronesia": ["Micronesia"],
  "Moldova": ["Moldova"],
  "Monaco": ["Monaco"],
  "Mongolia": ["Mongolia"],
  "Montenegro": ["Montenegro"],
  "Morocco": ["Morocco", "casablanca", "marrakech", "marrakesh", "rabat"],
  "Mozambique": ["Mozambique"],
  "Myanmar": ["Myanmar"],
  "Namibia": ["Namibia"],
  "Nauru": ["Nauru"],
  "Nepal": ["Nepal"],
  "Netherlands": ["Netherlands", "ams", "amsterdam", "rotterdam"],
  "New Zealand": ["New Zealand"],
  "Nicaragua": ["Nicaragua"],
  "Niger": ["Niger"],
  "Nigeria": ["Nigeria"],
  "North Korea": ["North Korea"],
  "North Macedonia": ["North Macedonia"],
  "Norway": ["Norway", "osl", "oslo"],
  "Oman": ["Oman"],
  "Pakistan": ["Pakistan"],
  "Palau": ["Palau"],
  "Palestine": ["Palestine"],
  "Panama": ["Panama"],
  "Papua New Guinea": ["Papua New Guinea"],
  "Paraguay": ["Paraguay"],
  "Peru": ["Peru"],
  "Philippines": ["Philippines"],
  "Poland": ["Poland", "krakow", "kraków", "krk", "warsaw", "warschau", "waw"],
  "Portugal": ["Portugal", "lis", "lisboa", "lisbon", "opo", "porto"],
  "Qatar": ["Qatar", "doh", "doha"],
  "Romania": ["Romania"],
  "Russia": ["Russia"],
  "Rwanda": ["Rwanda"],
  "Saint Kitts and Nevis": ["Saint Kitts and Nevis"],
  "Saint Lucia": ["Saint Lucia"],
  "Saint Vincent and the Grenadines": ["Saint Vincent and the Grenadines"],
  "Samoa": ["Samoa"],
  "San Marino": ["San Marino"],
  "Sao Tome and Principe": ["Sao Tome and Principe"],
  "Saudi Arabia": ["Saudi Arabia"],
  "Senegal": ["Senegal"],
  "Serbia": ["Serbia"],
  "Seychelles": ["Seychelles"],
  "Sierra Leone": ["Sierra Leone"],
  "Singapore": ["Singapore", "sin", "singapore"],
  "Slovakia": ["Slovakia"],
  "Slovenia": ["Slovenia"],
  "Solomon Islands": ["Solomon Islands"],
  "Somalia": ["Somalia"],
  "South Africa": ["South Africa"],
  "South Korea": ["South Korea", "icn", "korea", "seoul"],
  "South Sudan": ["South Sudan"],
  "Spain": ["Spain", "agp", "barcelona", "bcn", "ibiza", "mad", "madrid", "malaga", "mallorca", "málaga", "palma", "palma de mallorca", "pmi", "seville", "valencia"],
  "Sri Lanka": ["Sri Lanka"],
  "Sudan": ["Sudan"],
  "Suriname": ["Suriname"],
  "Sweden": ["Sweden", "arn", "stockholm"],
  "Switzerland": ["Switzerland", "geneva", "genf", "gva", "zrh", "zurich", "zürich"],
  "Syria": ["Syria"],
  "Tajikistan": ["Tajikistan"],
  "Tanzania": ["Tanzania"],
  "Thailand": ["Thailand", "bangkok", "bkk", "phuket"],
  "Timor-Leste": ["Timor-Leste"],
  "Togo": ["Togo"],
  "Tonga": ["Tonga"],
  "Trinidad and Tobago": ["Trinidad and Tobago"],
  "Tunisia": ["Tunisia", "djerba", "tunis"],
  "Turkey": ["Turkey", "ankara", "antalya", "ist", "istanbul"],
  "Turkmenistan": ["Turkmenistan"],
  "Tuvalu": ["Tuvalu"],
  "Uganda": ["Uganda"],
  "Ukraine": ["Ukraine"],
  "United Arab Emirates": ["United Arab Emirates", "abu dhabi", "auh", "dubai", "dxb", "uae"],
  "United Kingdom": ["United Kingdom", "edi", "edinburgh", "england", "great britain", "lgw", "lhr", "london", "man", "manchester", "scotland", "stn", "uk", "wales"],
  "United States": ["United States", "boston", "chicago", "ewr", "jfk", "las vegas", "lax", "los angeles", "mia", "miami", "new york", "ord", "san francisco", "sfo", "united states of america", "usa", "washington"],
  "Uruguay": ["Uruguay"],
  "Uzbekistan": ["Uzbekistan"],
  "Vanuatu": ["Vanuatu"],
  "Vatican City": ["Vatican City"],
  "Venezuela": ["Venezuela"],
  "Vietnam": ["Vietnam"],
  "Yemen": ["Yemen"],
  "Zambia": ["Zambia"],
  "Zimbabwe": ["Zimbabwe"],
};

export function normalizeCountryText(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .replace(/\bthe\b/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

function containsAlias(normalizedValue: string, normalizedAlias: string): boolean {
  if (!normalizedAlias) {
    return false;
  }

  return normalizedValue === normalizedAlias
    || normalizedValue.startsWith(`${normalizedAlias} `)
    || normalizedValue.endsWith(` ${normalizedAlias}`)
    || normalizedValue.includes(` ${normalizedAlias} `);
}

export function resolveCountryName(value: string, blockedCountries: readonly string[] = []): string | null {
  const normalizedValue = normalizeCountryText(value);

  if (!normalizedValue) {
    return null;
  }

  const blocked = new Set(blockedCountries);

  for (const country of WORLD_COUNTRIES) {
    if (blocked.has(country)) {
      continue;
    }

    const aliases = COUNTRY_DESTINATION_ALIASES[country] ?? [country];
    if (aliases.some((alias) => containsAlias(normalizedValue, normalizeCountryText(alias)))) {
      return country;
    }
  }

  return null;
}

export function uniqueCountries(values: readonly string[]): string[] {
  return [...new Set(values)].filter((country) => (WORLD_COUNTRIES as readonly string[]).includes(country));
}
