export interface HotelDestination {
  readonly name: string;
  readonly aliases?: readonly string[];
}

export const HOTEL_DESTINATIONS: readonly HotelDestination[] = [
  { name: 'Aachen' },
  { name: 'Aalborg' },
  { name: 'Aarhus', aliases: ['Århus'] },
  { name: 'Aberdeen' },
  { name: 'Alicante' },
  { name: 'Almere' },
  { name: 'Amersfoort' },
  { name: 'Amsterdam' },
  { name: 'Angers' },
  { name: 'Antwerp', aliases: ['Antwerpen', 'Anvers'] },
  { name: 'Antalya' },
  { name: 'Athens' },
  { name: 'Auckland' },
  { name: 'Avignon' },
  { name: 'Baden-Baden' },
  { name: 'Bangkok' },
  { name: 'Barcelona' },
  { name: 'Bari' },
  { name: 'Basel', aliases: ['Bâle'] },
  { name: 'Bath' },
  { name: 'Beijing' },
  { name: 'Belfast' },
  { name: 'Berlin' },
  { name: 'Bern', aliases: ['Berne'] },
  { name: 'Bergen' },
  { name: 'Bergamo' },
  { name: 'Bielefeld' },
  { name: 'Bilbao' },
  { name: 'Birmingham' },
  { name: 'Bonn' },
  { name: 'Bochum' },
  { name: 'Bologna' },
  { name: 'Boston' },
  { name: 'Bordeaux' },
  { name: 'Bremen' },
  { name: 'Brighton' },
  { name: 'Bristol' },
  { name: 'Brisbane' },
  { name: 'Brussels' },
  { name: 'Bruges', aliases: ['Brugge'] },
  { name: 'Brno' },
  { name: 'Budapest' },
  { name: 'Buenos Aires' },
  { name: 'Cairo' },
  { name: 'Cancun', aliases: ['Cancún'] },
  { name: 'Cape Town' },
  { name: 'Cardiff' },
  { name: 'Catania' },
  { name: 'Chicago' },
  { name: 'Clermont-Ferrand' },
  { name: 'Coimbra' },
  { name: 'Colombo' },
  { name: 'Copenhagen' },
  { name: 'Cork' },
  { name: 'Darmstadt' },
  { name: 'Dallas' },
  { name: 'Delft' },
  { name: 'Delhi', aliases: ['New Delhi'] },
  { name: 'Doha' },
  { name: 'Dortmund' },
  { name: 'Dresden' },
  { name: 'Dubai' },
  { name: 'Dublin' },
  { name: 'Duisburg' },
  { name: 'Düsseldorf', aliases: ['Dusseldorf', 'Duesseldorf'] },
  { name: 'Eindhoven' },
  { name: 'Edinburgh' },
  { name: 'Essen' },
  { name: 'Exeter' },
  { name: 'Faro' },
  { name: 'Florence', aliases: ['Firenze'] },
  { name: 'Frankfurt', aliases: ['Frankfurt am Main'] },
  { name: 'Freiburg' },
  { name: 'Gdańsk', aliases: ['Gdansk', 'Danzig'] },
  { name: 'Geneva', aliases: ['Genf'] },
  { name: 'Genoa', aliases: ['Genova'] },
  { name: 'Ghent', aliases: ['Gent', 'Gand'] },
  { name: 'Glasgow' },
  { name: 'Gothenburg', aliases: ['Göteborg', 'Goteborg'] },
  { name: 'Graz' },
  { name: 'Groningen' },
  { name: 'Haarlem' },
  { name: 'Halle' },
  { name: 'Hamburg' },
  { name: 'Hanover', aliases: ['Hannover'] },
  { name: 'Hanoi' },
  { name: 'Heidelberg' },
  { name: 'Helsinki' },
  { name: 'Heraklion', aliases: ['Iraklio'] },
  { name: 'Hong Kong' },
  { name: 'Honolulu' },
  { name: 'Houston' },
  { name: 'Innsbruck' },
  { name: 'Istanbul' },
  { name: 'Jakarta' },
  { name: 'Johannesburg' },
  { name: 'Karlsruhe' },
  { name: 'Kassel' },
  { name: 'Kiel' },
  { name: 'Klagenfurt' },
  { name: 'Köln', aliases: ['Koln', 'Koeln', 'Cologne'] },
  { name: 'Krakow', aliases: ['Kraków'] },
  { name: 'Kyoto' },
  { name: 'Las Vegas' },
  { name: 'La Rochelle' },
  { name: 'Lausanne' },
  { name: 'Leeds' },
  { name: 'Leicester' },
  { name: 'Leipzig' },
  { name: 'Lille' },
  { name: 'Limerick' },
  { name: 'Linz' },
  { name: 'Lisbon', aliases: ['Lisboa'] },
  { name: 'Liverpool' },
  { name: 'Ljubljana' },
  { name: 'London' },
  { name: 'Los Angeles' },
  { name: 'Lübeck', aliases: ['Luebeck', 'Lubeck'] },
  { name: 'Lugano' },
  { name: 'Lyon' },
  { name: 'Madrid' },
  { name: 'Malaga', aliases: ['Málaga'] },
  { name: 'Malmö', aliases: ['Malmo'] },
  { name: 'Manchester' },
  { name: 'Marseille' },
  { name: 'Marrakech' },
  { name: 'Melbourne' },
  { name: 'Metz' },
  { name: 'Mexico City', aliases: ['Ciudad de Mexico', 'Ciudad de México'] },
  { name: 'Miami' },
  { name: 'Milan', aliases: ['Milano'] },
  { name: 'Montreal', aliases: ['Montréal'] },
  { name: 'Montpellier' },
  { name: 'Moscow' },
  { name: 'Mumbai' },
  { name: 'Münster', aliases: ['Muenster', 'Munster'] },
  { name: 'München', aliases: ['Munich', 'Muenchen', 'Munchen'] },
  { name: 'Nantes' },
  { name: 'Naples', aliases: ['Napoli'] },
  { name: 'New Orleans' },
  { name: 'New York' },
  { name: 'Newcastle' },
  { name: 'Nice' },
  { name: 'Nottingham' },
  { name: 'Nuremberg', aliases: ['Nürnberg', 'Nuernberg', 'Nurnberg'] },
  { name: 'Odense' },
  { name: 'Olomouc' },
  { name: 'Orlando' },
  { name: 'Osaka' },
  { name: 'Oslo' },
  { name: 'Oxford' },
  { name: 'Palermo' },
  { name: 'Paris' },
  { name: 'Parma' },
  { name: 'Pisa' },
  { name: 'Philadelphia' },
  { name: 'Portsmouth' },
  { name: 'Porto' },
  { name: 'Prague', aliases: ['Praha'] },
  { name: 'Reims' },
  { name: 'Rennes' },
  { name: 'Rhodes', aliases: ['Rodos'] },
  { name: 'Rio de Janeiro' },
  { name: 'Rome', aliases: ['Roma'] },
  { name: 'Rotterdam' },
  { name: 'Salzburg' },
  { name: 'San Diego' },
  { name: 'San Francisco' },
  { name: 'San Sebastián', aliases: ['San Sebastian', 'Donostia'] },
  { name: 'Santiago de Compostela' },
  { name: 'São Paulo', aliases: ['Sao Paulo'] },
  { name: 'Seattle' },
  { name: 'Seoul' },
  { name: 'Seville', aliases: ['Sevilla'] },
  { name: 'Shanghai' },
  { name: 'Sheffield' },
  { name: 'Singapore' },
  { name: 'Southampton' },
  { name: 'Split' },
  { name: 'Stockholm' },
  { name: 'Strasbourg' },
  { name: 'Stuttgart' },
  { name: 'Sydney' },
  { name: 'Taipei' },
  { name: 'Tampere' },
  { name: 'Thessaloniki' },
  { name: 'Tokyo' },
  { name: 'Toulouse' },
  { name: 'Toronto' },
  { name: 'Tromsø', aliases: ['Tromso'] },
  { name: 'Trondheim' },
  { name: 'Turin', aliases: ['Torino'] },
  { name: 'Turku' },
  { name: 'Utrecht' },
  { name: 'Valencia' },
  { name: 'Vancouver' },
  { name: 'Venice', aliases: ['Venezia'] },
  { name: 'Verona' },
  { name: 'Vienna', aliases: ['Wien'] },
  { name: 'Warsaw', aliases: ['Warszawa'] },
  { name: 'Wrocław', aliases: ['Wroclaw', 'Breslau'] },
  { name: 'Zagreb' },
  { name: 'Zaragoza' },
  { name: 'Zurich', aliases: ['Zürich', 'Zuerich'] },
  { name: 'Augsburg' },
  { name: 'Braunschweig' },
  { name: 'Chemnitz' },
  { name: 'Erfurt' },
  { name: 'Gelsenkirchen' },
  { name: 'Jena' },
  { name: 'Mainz' },
  { name: 'Magdeburg' },
  { name: 'Mannheim' },
  { name: 'Mönchengladbach', aliases: ['Moenchengladbach', 'Monchengladbach'] },
  { name: 'Oberhausen' },
  { name: 'Potsdam' },
  { name: 'Regensburg' },
  { name: 'Rostock' },
  { name: 'Saarbrücken', aliases: ['Saarbruecken', 'Saarbrucken'] },
  { name: 'Wiesbaden' },
  { name: 'Wuppertal' },
  { name: 'Amiens' },
  { name: 'Brest' },
  { name: 'Dijon' },
  { name: 'Grenoble' },
  { name: 'Le Havre' },
  { name: 'Nancy' },
  { name: 'Nîmes', aliases: ['Nimes'] },
  { name: 'Orléans', aliases: ['Orleans'] },
  { name: 'Rouen' },
  { name: 'Saint-Étienne', aliases: ['Saint Etienne', 'St Etienne'] },
  { name: 'Toulon' },
  { name: 'Tours' },
  { name: 'Trieste' },
  { name: 'Padua', aliases: ['Padova'] },
  { name: 'Perugia' },
  { name: 'Rimini' },
  { name: 'Siena' },
  { name: 'Córdoba', aliases: ['Cordoba'] },
  { name: 'Granada' },
  { name: 'Murcia' },
  { name: 'Palma de Mallorca', aliases: ['Palma'] },
  { name: 'Toledo' },
  { name: 'Bilbao' },
  { name: 'The Hague', aliases: ['Den Haag', 's Gravenhage'] },
  { name: 'Leiden' },
  { name: 'Maastricht' },
  { name: 'Nijmegen' },
  { name: 'Tilburg' },
  { name: 'Arnhem' },
  { name: 'Breda' },
  { name: 'Leuven' },
  { name: 'Liège', aliases: ['Liege', 'Luik'] },
  { name: 'Namur', aliases: ['Namen'] },
  { name: 'Ostend', aliases: ['Oostende'] },
  { name: 'Mechelen' },
  { name: 'Sankt Pölten', aliases: ['St Polten', 'Sankt Poelten'] },
  { name: 'Villach' },
  { name: 'Winterthur' },
  { name: 'Lucerne', aliases: ['Luzern'] },
  { name: 'St. Gallen', aliases: ['Saint Gallen'] },
  { name: 'Interlaken' },
  { name: 'Katowice' },
  { name: 'Łódź', aliases: ['Lodz'] },
  { name: 'Poznań', aliases: ['Poznan'] },
  { name: 'Szczecin' },
  { name: 'Lublin' },
  { name: 'Bydgoszcz' },
  { name: 'Plzeň', aliases: ['Plzen', 'Pilsen'] },
  { name: 'České Budějovice', aliases: ['Ceske Budejovice'] },
  { name: 'Karlovy Vary', aliases: ['Carlsbad'] },
  { name: 'Guimarães', aliases: ['Guimaraes'] },
  { name: 'Braga' },
  { name: 'Aveiro' },
  { name: 'Évora', aliases: ['Evora'] },
  { name: 'Patras' },
  { name: 'Volos' },
  { name: 'Larissa' },
  { name: 'Uppsala' },
  { name: 'Lund' },
  { name: 'Umeå', aliases: ['Umea'] },
  { name: 'Stavanger' },
  { name: 'Kristiansand' },
  { name: 'Esbjerg' },
  { name: 'Roskilde' },
  { name: 'Vantaa' },
  { name: 'Espoo' },
  { name: 'Pécs', aliases: ['Pecs'] },
  { name: 'Szeged' },
  { name: 'Debrecen' },
  { name: 'Galway' },
  { name: 'Kilkenny' },
  { name: 'Cambridge' },
  { name: 'York' },
  { name: 'Inverness' },
  { name: 'Stirling' },
  { name: 'Dubrovnik' },
  { name: 'Rijeka' },
  { name: 'Zadar' },
  { name: 'Pula' },
  { name: 'Ankara' },
  { name: 'Izmir', aliases: ['İzmir'] },
  { name: 'Bursa' },
  { name: 'Konya' },
  { name: 'Bodrum' },
  { name: 'Warsaw', aliases: ['Warszawa'] },
  { name: 'Washington' },
];

export const HOTEL_DESTINATION_NAMES: readonly string[] = uniqueDestinations(HOTEL_DESTINATIONS).map(
  (destination) => destination.name
);

export function getHotelDestinationSuggestions(query: string, limit = 8): string[] {
  const normalizedQuery = normalizeDestinationText(query);

  if (!normalizedQuery) {
    return [];
  }

  return uniqueDestinations(HOTEL_DESTINATIONS)
    .map((destination) => ({
      destination,
      rank: getDestinationMatchRank(destination, normalizedQuery),
    }))
    .filter((match) => match.rank >= 0)
    .sort((a, b) => a.rank - b.rank)
    .map((match) => match.destination)
    .map((destination) => destination.name)
    .slice(0, limit);
}

function getDestinationMatchRank(destination: HotelDestination, normalizedQuery: string): number {
  const terms = getDestinationSearchTerms(destination);

  if (terms.some((term) => term.startsWith(normalizedQuery))) {
    return 0;
  }

  if (terms.some((term) => term.includes(normalizedQuery))) {
    return 1;
  }

  return -1;
}

function getDestinationSearchTerms(destination: HotelDestination): string[] {
  return [destination.name, ...(destination.aliases ?? [])].map(normalizeDestinationText);
}

function uniqueDestinations(destinations: readonly HotelDestination[]): HotelDestination[] {
  const seenDestinations = new Set<string>();

  return destinations.filter((destination) => {
    const normalizedName = normalizeDestinationText(destination.name);

    if (!normalizedName || seenDestinations.has(normalizedName)) {
      return false;
    }

    seenDestinations.add(normalizedName);
    return true;
  });
}

function normalizeDestinationText(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/ä/g, 'ae')
    .replace(/ö/g, 'oe')
    .replace(/ü/g, 'ue')
    .replace(/ß/g, 'ss')
    .normalize('NFD')
    .replace(/\p{Diacritic}/gu, '')
    .replace(/[^a-z0-9]+/g, ' ');
}
