export const RECOMMENDED_EXPERIENCE_CITY_BATCH_SIZE = 8;

export const RECOMMENDED_EXPERIENCE_EUROPEAN_CITIES = [
  'Berlin',
  'Munich',
  'Hamburg',
  'Cologne',
  'Barcelona',
  'Madrid',
  'Valencia',
  'Seville',
  'Rome',
  'Milan',
  'Florence',
  'Naples',
  'Paris',
  'Lyon',
  'Marseille',
  'Nice',
  'Amsterdam',
  'Rotterdam',
  'Brussels',
  'Antwerp',
  'Vienna',
  'Salzburg',
  'Prague',
  'Budapest',
  'Lisbon',
  'Porto',
  'Copenhagen',
  'Stockholm',
  'Oslo',
  'Dublin',
  'Athens',
  'Zurich',
] as const;
